// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FooServiceClient is the client API for FooService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FooServiceClient interface {
	AddFoo(ctx context.Context, in *Foo, opts ...grpc.CallOption) (*Foo, error)
	EditFoo(ctx context.Context, in *Foo, opts ...grpc.CallOption) (*Foo, error)
	DeleteFoo(ctx context.Context, in *Select, opts ...grpc.CallOption) (*Foo, error)
	GetDetailFoo(ctx context.Context, in *Select, opts ...grpc.CallOption) (*Foo, error)
	GetAllFoo(ctx context.Context, in *Pagination, opts ...grpc.CallOption) (*Foos, error)
}

type fooServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFooServiceClient(cc grpc.ClientConnInterface) FooServiceClient {
	return &fooServiceClient{cc}
}

func (c *fooServiceClient) AddFoo(ctx context.Context, in *Foo, opts ...grpc.CallOption) (*Foo, error) {
	out := new(Foo)
	err := c.cc.Invoke(ctx, "/api.v1.FooService/AddFoo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fooServiceClient) EditFoo(ctx context.Context, in *Foo, opts ...grpc.CallOption) (*Foo, error) {
	out := new(Foo)
	err := c.cc.Invoke(ctx, "/api.v1.FooService/EditFoo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fooServiceClient) DeleteFoo(ctx context.Context, in *Select, opts ...grpc.CallOption) (*Foo, error) {
	out := new(Foo)
	err := c.cc.Invoke(ctx, "/api.v1.FooService/DeleteFoo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fooServiceClient) GetDetailFoo(ctx context.Context, in *Select, opts ...grpc.CallOption) (*Foo, error) {
	out := new(Foo)
	err := c.cc.Invoke(ctx, "/api.v1.FooService/GetDetailFoo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fooServiceClient) GetAllFoo(ctx context.Context, in *Pagination, opts ...grpc.CallOption) (*Foos, error) {
	out := new(Foos)
	err := c.cc.Invoke(ctx, "/api.v1.FooService/GetAllFoo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FooServiceServer is the server API for FooService service.
// All implementations should embed UnimplementedFooServiceServer
// for forward compatibility
type FooServiceServer interface {
	AddFoo(context.Context, *Foo) (*Foo, error)
	EditFoo(context.Context, *Foo) (*Foo, error)
	DeleteFoo(context.Context, *Select) (*Foo, error)
	GetDetailFoo(context.Context, *Select) (*Foo, error)
	GetAllFoo(context.Context, *Pagination) (*Foos, error)
}

// UnimplementedFooServiceServer should be embedded to have forward compatible implementations.
type UnimplementedFooServiceServer struct {
}

func (UnimplementedFooServiceServer) AddFoo(context.Context, *Foo) (*Foo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFoo not implemented")
}
func (UnimplementedFooServiceServer) EditFoo(context.Context, *Foo) (*Foo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditFoo not implemented")
}
func (UnimplementedFooServiceServer) DeleteFoo(context.Context, *Select) (*Foo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFoo not implemented")
}
func (UnimplementedFooServiceServer) GetDetailFoo(context.Context, *Select) (*Foo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDetailFoo not implemented")
}
func (UnimplementedFooServiceServer) GetAllFoo(context.Context, *Pagination) (*Foos, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllFoo not implemented")
}

// UnsafeFooServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FooServiceServer will
// result in compilation errors.
type UnsafeFooServiceServer interface {
	mustEmbedUnimplementedFooServiceServer()
}

func RegisterFooServiceServer(s grpc.ServiceRegistrar, srv FooServiceServer) {
	s.RegisterService(&FooService_ServiceDesc, srv)
}

func _FooService_AddFoo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Foo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FooServiceServer).AddFoo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.FooService/AddFoo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FooServiceServer).AddFoo(ctx, req.(*Foo))
	}
	return interceptor(ctx, in, info, handler)
}

func _FooService_EditFoo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Foo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FooServiceServer).EditFoo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.FooService/EditFoo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FooServiceServer).EditFoo(ctx, req.(*Foo))
	}
	return interceptor(ctx, in, info, handler)
}

func _FooService_DeleteFoo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Select)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FooServiceServer).DeleteFoo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.FooService/DeleteFoo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FooServiceServer).DeleteFoo(ctx, req.(*Select))
	}
	return interceptor(ctx, in, info, handler)
}

func _FooService_GetDetailFoo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Select)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FooServiceServer).GetDetailFoo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.FooService/GetDetailFoo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FooServiceServer).GetDetailFoo(ctx, req.(*Select))
	}
	return interceptor(ctx, in, info, handler)
}

func _FooService_GetAllFoo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pagination)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FooServiceServer).GetAllFoo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.FooService/GetAllFoo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FooServiceServer).GetAllFoo(ctx, req.(*Pagination))
	}
	return interceptor(ctx, in, info, handler)
}

// FooService_ServiceDesc is the grpc.ServiceDesc for FooService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FooService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.FooService",
	HandlerType: (*FooServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddFoo",
			Handler:    _FooService_AddFoo_Handler,
		},
		{
			MethodName: "EditFoo",
			Handler:    _FooService_EditFoo_Handler,
		},
		{
			MethodName: "DeleteFoo",
			Handler:    _FooService_DeleteFoo_Handler,
		},
		{
			MethodName: "GetDetailFoo",
			Handler:    _FooService_GetDetailFoo_Handler,
		},
		{
			MethodName: "GetAllFoo",
			Handler:    _FooService_GetAllFoo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "foo.proto",
}
